
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { UIProvider} from "@/hooks/HideModal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className=" h-full antialiased"
    >

      <body className="min-h-full flex flex-col">
          <UIProvider>
        {children}</UIProvider>
        <ToastContainer position="top-right" theme="colored" />
      </body>
    </html>
  );
}